### PR TITLE
clean up learn page

### PR DESCRIPTION
**Pull request by abyrd**

### CODE REVIEW

**Comment by trevorgerhardt** [comment]
#### 📝Changed routes:


| [**/learn**](https://conveyal-com-8938ojnci.vercel.app/learn) |
|:-:|
|<a href="https://conveyal-com-8938ojnci.vercel.app/learn">Screenshot of /learn</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/BKxWFxNLyotyzBhvo9si6aLCpwA_.png">(view full size)</a> |







Commit b7759910667e531192ecd25f0d6dcac863e9b127 (https://conveyal-com-8938ojnci.vercel.app).

**Comment by abyrd** [comment]
Taking another look at the preview, I think this is in fact ready for merge whenever you're ready. It might look better with some more illustrations but those can be refreshed later. I liked having the OSI open source logo in the "openness" section (as on https://www.conveyal.com/analysis) but don't see a way to get the logo in that position with markdown.

**Comment by abyrd** [comment]
Actually I'm adding a couple of images now, including one that was already in the repo and some from the old analysis page.

**Comment by abyrd** [comment]
The images aren't the best illustrations of the text, but at least it looks a little more lively now. I've included the OSI logo but couldn't get it to float the way I was aiming for with `style={{float: 'left'}}`. If you want to add this logo give it a try. Otherwise feel free to merge.

**Review by trevorgerhardt — APPROVED** [review]

**Pull request merged**
